tape/src/main/java/com/squareup/tape/QueueFile.java
tape/src/test/java/com/squareup/tape/QueueFileTest.java

Return a count of the number of elements visited.

---

tape/src/main/java/com/squareup/tape/FileObjectQueue.java
tape/src/main/java/com/squareup/tape/QueueFile.java

Close if this isn't worthwhile. :)

Remove need for synthetic accessor methods

---

tape/src/main/java/com/squareup/tape/QueueFile.java
tape/src/test/java/com/squareup/tape/QueueFileTest.java

QueueFile now implements `Iterable<byte[]>`.
The iterator also permits removing elements from the head. This make it easier for clients to process and discard elements one at a time.
```java
Iterator<byte[]> iterator = queueFile.iterator();
while (iterator.hasNext()) {
byte[] data = iterator.next();
process(data);
iterator.remove();
}
```
The iterator also disallows modifications to the QueueFile while it is being iterated.

Make QueueFile iterable.

---

tape/src/main/java/com/squareup/tape/Private.java
tape/src/main/java/com/squareup/tape/QueueFile.java

There were a couple more places we could reduce it with the addition of #90.
cc @NightlyNexus

Nuke creation of synthetic accessor methods

---

tape/src/main/java/com/squareup/tape/QueueFile.java
tape/src/test/java/com/squareup/tape/QueueFileTest.java

Remove element lengths from toString().

---

pom.xml
tape/pom.xml
tape/src/main/java/com/squareup/tape/QueueFile.java
tape/src/test/java/com/squareup/tape/QueueFileTest.java

Closes #52.
I don't think this is necessarily the final API. Just an implementation of the behavior.

Expose option to not zero out erased elements.

---

tape/src/main/java/com/squareup/tape/QueueFile.java

Remove synchronized from QueueFile

---

tape/src/main/java/com/squareup/tape/FileObjectQueue.java
tape/src/main/java/com/squareup/tape/InMemoryObjectQueue.java
tape/src/main/java/com/squareup/tape/ObjectQueue.java
tape/src/test/java/com/squareup/tape/FileObjectQueueTest.java

Promote FileObjectQueue methods to ObjectQueue

---

checkstyle.xml
tape/build.gradle
tape/src/test/java/com/squareup/tape/ObjectQueueTest.java
tape/src/test/java/com/squareup/tape/QueueFileLoadingTest.java
tape/src/test/java/com/squareup/tape/QueueFileTest.java
tape/src/test/java/com/squareup/tape/QueueTestUtils.java

This actually caught a few violations (I copied the config from Picasso since I figured it was more up to date).

Setup checkstyle with Gradle

---

tape/src/main/java/com/squareup/tape2/QueueFile.java

The existing code seems wrong.
Probably the result of copy-pasting?

fix QueueFile.readLong()

---

README.md

clarify file system requirements in readme

---

tape/src/main/java/com/squareup/tape2/FileObjectQueue.java
tape/src/main/java/com/squareup/tape2/InMemoryObjectQueue.java
tape/src/main/java/com/squareup/tape2/ObjectQueue.java

As per https://github.com/square/tape/pull/124

ObjectQueue#file exposes QueueFile instead of File

---

tape/src/main/java/com/squareup/tape2/InMemoryObjectQueue.java

This fixes the horrid O(n^2) iterator performance to O(n) by using a delegate iterator on the underlying collection. It also reduces the overhead and improves locality of the backing collection.

Switch in-memory queue to superior array-backed deque.

---

build.gradle
tape/src/test/java/com/squareup/tape2/ObjectQueueTest.java

Add Error Prone

---

tape/build.gradle
tape/src/test/java/com/squareup/tape2/QueueTestUtils.java

Replace commons-io with Okio.

---

tape/build.gradle
tape/src/test/java/com/squareup/tape2/ObjectQueueTest.java
tape/src/test/java/com/squareup/tape2/QueueFileTest.java

Replace FEST with Truth.

---

README.md
tape/src/test/java/com/squareup/tape2/ObjectQueueTest.java
website/index.html

Remove legacy examples and references from the website and Readme.
Also updates the maven artifacts for v2.
Adds usage examples to the Readme.

Update website and Readme.

---

tape/src/main/java/com/squareup/tape2/FileObjectQueue.java
tape/src/main/java/com/squareup/tape2/InMemoryObjectQueue.java
tape/src/main/java/com/squareup/tape2/QueueFile.java
tape/src/test/java/com/squareup/tape2/QueueFileTest.java

Implement toString.

---

README.md

sorry for the nitpick. close it if it's too much noise for the readme.

Flush Sink in MoshiConverter example.

---

CONTRIBUTING.md

Remove references to building with maven.

---

build.gradle
tape/src/test/java/com/squareup/tape2/QueueFileTest.java

Instead of wildcarding.
Sorry about that. I did it in LeakCanary, too.

Specify Error Prone version.
